[package]
name = "yew-app2"
version = "0.1.0"
authors = ["Ethan Tang <ethanyidong@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.58"
yew = { version = "0.13", features = ["web_sys"] }
